# Generated by Django 5.1.2 on 2024-11-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoHUDApp', '0002_profile_delete_userregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
