# Generated by Django 5.1.2 on 2024-11-04 07:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoHUDApp', '0003_profile_login_time_profile_logout_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='login_time',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='logout_time',
        ),
        migrations.CreateModel(
            name='LoginLogoutEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=10)),
                ('event_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='DjangoHUDApp.profile')),
            ],
        ),
    ]
