# Generated by Django 5.1.3 on 2024-11-11 06:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoHUDApp', '0004_remove_profile_login_time_remove_profile_logout_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('trainer_name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('duration', models.DurationField()),
                ('location', models.CharField(max_length=200)),
                ('participants_count', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('feedback', models.TextField(choices=[('Not Interested', 'Not Interested'), ('Schedule', 'Schedule'), ('Fixed Appointment', 'Fixed Appointment'), ('Presentation', 'Presentation'), ('Presentation Completed', 'Presentation Completed'), ('MOU', 'MOU'), ('Trainee', 'Trainee'), ('Closure', 'Closure')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationDataAlt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=255)),
                ('spoc_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[6-9]\\d{9}$', 'Phone number must be 10 digits and start with 6, 7, 8, or 9.')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('website', models.URLField()),
                ('source_data', models.CharField(choices=[('Referral', 'Referral'), ('Advertisement', 'Advertisement'), ('Social Media', 'Social Media')], max_length=255)),
                ('status', models.CharField(choices=[('no_response', 'NO response'), ('wrong_response', 'Wrong response'), ('callback', 'Callback'), ('initiated', 'Initiated'), ('follow_up', 'Follow Up'), ('demo', 'Demo'), ('closure', 'Closure')], max_length=255)),
                ('feedback', models.CharField(choices=[('Not Interested', 'Not Interested'), ('Schedule', 'Schedule'), ('Fixed Appointment', 'Fixed Appointment'), ('Presentation', 'Presentation'), ('Presentation Completed', 'Presentation Completed'), ('MOU', 'MOU'), ('Trainee', 'Trainee'), ('Closure', 'Closure')], max_length=255)),
                ('remark', models.TextField()),
                ('reference', models.TextField()),
                ('callback_date', models.DateTimeField(blank=True, null=True)),
                ('initiated_date', models.DateTimeField(blank=True, null=True)),
                ('followup_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlacementTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=255)),
                ('spoc_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[6-9]\\d{9}$', 'Phone number must be 10 digits and start with 6, 7, 8, or 9.')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('website', models.URLField()),
                ('source_data', models.CharField(choices=[('Referral', 'Referral'), ('Advertisement', 'Advertisement'), ('Social Media', 'Social Media')], max_length=255)),
                ('status', models.CharField(choices=[('no_response', 'NO response'), ('wrong_response', 'Wrong response'), ('callback', 'Callback'), ('initiated', 'Initiated'), ('follow_up', 'Follow Up'), ('demo', 'Demo'), ('closure', 'Closure')], max_length=255)),
                ('feedback', models.CharField(choices=[('Not Interested', 'Not Interested'), ('Schedule', 'Schedule'), ('Fixed Appointment', 'Fixed Appointment'), ('Presentation', 'Presentation'), ('Presentation Completed', 'Presentation Completed'), ('MOU', 'MOU'), ('Trainee', 'Trainee'), ('Closure', 'Closure')], max_length=255)),
                ('remark', models.TextField()),
                ('reference', models.TextField()),
                ('callback_date', models.DateTimeField(blank=True, null=True)),
                ('initiated_date', models.DateTimeField(blank=True, null=True)),
                ('followup_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_name', models.CharField(max_length=255)),
                ('trainer_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('duration', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('feedback', models.TextField(choices=[('Not Interested', 'Not Interested'), ('Schedule', 'Schedule'), ('Fixed Appointment', 'Fixed Appointment'), ('Presentation', 'Presentation'), ('Presentation Completed', 'Presentation Completed'), ('MOU', 'MOU'), ('Trainee', 'Trainee'), ('Closure', 'Closure')], max_length=200)),
                ('remarks', models.TextField()),
                ('reference', models.CharField(max_length=255)),
            ],
        ),
    ]
